### ISSUE TITLE
[Feature] Chest/Door Locks

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#101]
Submitted By:
TypicalChaos724

Feature Description:
Simple sign locks for chests and doors.

Benefit to the entire server:
will only allow entry by someone that has been added to the sign(s) by name. This will keep theft down from new players that join towns and aren't fully trusted, but are being given a chance.

Effect on game balance:
I do not think it will at all. But I'm unsure of the siege mechanics.

Type Key:
[FEAT]

**Comment by Ghostlyfire99** [comment]
The reason why this will be problematic is for ruined towns. The issue is that sometimes, when the sieged town doesn't have much essence in bank, it will fall in ruin and that would mean that the victor would be able to raid said town. Having a lock would stop the rightful winners to their spoils. There's also an issue for abandoned bases. While there is already an issue for old bases that do not bring anything to this server, having locks on certain chests would require staff with the moderator status to invest time into this extra issue. For a fix for your problem, you can turn the permissions off for your town and give plots to your members (all commands are in the compass)

**Comment by Barbadosian** [comment]
Thanks Ghostly for writing up the explanation! And yes they are really on the point.

In summary, having another set of land claim/item protection system will add to the already steep learning curve of towny, and make mayor/resident relationship unnecessarily complicated as players can really grief the entire town by placing doors all over. To prevent that we will have to give mayor the perm to destroy personal locks, which then render the system really meaningless.
