### ISSUE TITLE
[Feature] A command tutorial center

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#102]
Submitted By:
Secklow

Feature Description:
Have signs up in the spawn where players have to pass or walk through to read the list of essential commands.

Benefit to the entire server:
Everyone new can collectively collect information on important and essential commands.

Effect on game balance:
Everyone should have access to the knowledge of ALL usable commands by new players. And knowledge about titles and their new commands (if any) would be useful and maybe profitable for the server ($$$) as well.

Type Key:
[FEAT]

**Comment by Ghostlyfire99** [comment]
While there is the compass which fills that role, I have to agree that there isn't anything which explains the existence of said compass. Also, putting it in the tutorial would not be advised because people just don't read the text that is there. An idea for where the text should be placed would be next to the return to earth villager at /spawn.

**Comment by Barbadosian** [comment]
This is on track for development. Ghostly is going to either incorporate it into the current tutorial book or make a separate one for basic commands.

**Comment by Barbadosian** [comment]
This is officially a thing. Thank you for the cool suggestions! We are going to continuously make it better.
