### ISSUE TITLE
[Bug] I didn't get any role after I linked with /link and I can't toggle the channels with reacting with the reactions.

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#78]
Submitted By:
Noobie_White

Game Version/Launcher:
1.16.3 , forge 

Bug Description:
I didn't get any role after I linked with /link. I think I should get a linked role. 
I can't toggle the Issue Updates and Live-Chat channels with  reacting with the reactions.
I don't have permission to view the message history of announcements channel.
I clicked the :book: to agree the rules.

Type Key:
[BUG]

**Comment by benevolent2012** [comment]
I am working on a better method of linking. Every player will have to re-link their accounts when I do complete that, but players will be rewarded for linking. Should be ready in a week or two.

Thank you for raising the issue. The permissions have been fixed so that you should be able to view the announcement channel. Everyone should have access to issue updates. 
Live chat has been hidden, as it hasn't been updated to match the new server structure. Simply teleporting to a different world will register it as leaving the server, which is not the case.
